# Generated by Django 5.2.17 on 2026-09-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
